# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
source 'http://192.168.1.18/bichan_coms/pod_specs’

inhibit_all_warnings!

target 'BCNetworkSDK' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BCNetworkSDK

    pod 'AFNetworking', '~> 3.1.0'
    pod 'CocoaLumberjack', '1.9.1'

end

  target 'BCNetworkSDKTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

target 'Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo
    inherit! :search_paths


end
