# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/QLwangqinghai/pod.git’

#inhibit_all_warnings!

target 'LiveTeaching' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for LiveTeaching


    pod 'CCFoundation', :path => '../CCFoundation'
    pod 'Basic', :path => '../Basic'
    pod 'SITP', :path => '../SITP'
    pod 'UIFoundation', :path => '../UIFoundation'
    pod 'FileService', :path => '../FileService'
    pod 'DrawingBoard', :path => '../DrawingBoard'


end