# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'


target 'RTC' do
  platform :ios, '9.0'
  pod 'GoogleWebRTC'

  
end