# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/QLwangqinghai/pod.git’

#inhibit_all_warnings!

target 'LiveTeaching' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for LiveTeaching


    pod 'CCFoundation', :path => '../../../Common/CCFoundation'
    pod 'Basic', :path => '../../../Common/Basic'
    pod 'SITP', :path => '../../../Common/SITP'
    pod 'FileService', :path => '../../../Common/FileService'
    pod 'UIFoundation', :path => '../UIFoundation'
    #pod 'DrawingBoard', :path => '../DrawingBoard'

    pod 'SwiftyBeaver'
    pod 'YYText'

end
